### ISSUE TITLE
Parameter naming for Site

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simulation_model#7]
This is to discuss parameter names related to site and suggestions to change. I would like to have explicit and full names to be as clear as possible.

Reference points: I first thought it should be named like `center_altitude`, `center_longitude`, .. but it is not always the center of the layouts. I suggest therefore (comment if it is too long):

- `reference_point_altitude` replaces `altitude`
- `reference_point_longitude` replaces `ref_long`
- `reference_point_latitude` replaces `ref_lat`
- `EPSG_code` replaces `EPSG`

More CORSIKA related:

- `corsika_observation_level` replaces `corsika_obs_level` (and `OBSLEVEL`)
- `corsika_sphere_radius` does not change

Structure related:

- `telescope_axes_height` replaces `corsika_sphere_center` (discussed earlier in the context of the workflows)

Atmosphere related:

- `atmospheric_transmission` does not change (or do we need to add a `_file`? Don't think so)
- `atmospheric_profile` does not change
- `magnetic_field` is a string of two numbers (e.g. `20.552 -9.367`), do we want to keep that? 

`array_triggers` is part of the site parameters. Do we want to keep this? It feels a bit out of place.

**Comment by orelgueta** [comment]
Agree with everything you wrote. Two small comments:

> * `magnetic_field` is a string of two numbers (e.g. `20.552 -9.367`), do we want to keep that?

I think it might be good to split actually. It might be useful to have easy "access" to the float values.

> `array_triggers` is part of the site parameters. Do we want to keep this? It feels a bit out of place.

Honestly I am not sure where to put it. It is more of a "run" parameter because it depends on the exact layout simulated. I do think the "sites" collection is the most appropriate place for now, but in the future it might move to a different collection with other similar parameters.
